# Generated by Django 4.2.11 on 2024-06-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.TextField(max_length=20)),
                ('user_id', models.TextField(max_length=9)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
