# Generated by Django 4.2.11 on 2024-06-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='user_id',
        ),
    ]
