# Generated by Django 4.2.11 on 2024-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_graphic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='user',
            field=models.TextField(max_length=40),
        ),
    ]
