# Generated by Django 4.2.11 on 2024-06-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_graphic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='customs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='graphic',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
